name: ccu_toolbox
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.5+7

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.3
  intl: ^0.16.1
  http: ^0.12.0+4
  shared_preferences: ^0.5.6+1
  html: ^0.14.0+3
  flutter_html: ^0.11.1
  html_character_entities: ^0.1.2+3
  url_launcher: ^5.4.1
  flutter_widgets: ^0.1.10
  table_calendar: ^2.2.2
  csv: ^4.0.3
  flutter_svg: ^0.17.1
  sqflite: ^1.2.1
  path: ^1.6.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true
  ios: true
  image_path: "dev_assets/icon.png"
  adaptive_icon_background: "#CEEBE9"
  adaptive_icon_foreground: "dev_assets/icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/20191128_175222.jpg
   - assets/schedule/108_schedule.csv
   - assets/images/file_extension_icon/3ds.svg
   - assets/images/file_extension_icon/aac.svg
   - assets/images/file_extension_icon/ai.svg
   - assets/images/file_extension_icon/avi.svg
   - assets/images/file_extension_icon/bmp.svg
   - assets/images/file_extension_icon/cad.svg
   - assets/images/file_extension_icon/cdr.svg
   - assets/images/file_extension_icon/css.svg
   - assets/images/file_extension_icon/dat.svg
   - assets/images/file_extension_icon/dll.svg
   - assets/images/file_extension_icon/dmg.svg
   - assets/images/file_extension_icon/doc.svg
   - assets/images/file_extension_icon/eps.svg
   - assets/images/file_extension_icon/fla.svg
   - assets/images/file_extension_icon/flv.svg
   - assets/images/file_extension_icon/gif.svg
   - assets/images/file_extension_icon/html.svg
   - assets/images/file_extension_icon/indd.svg
   - assets/images/file_extension_icon/iso.svg
   - assets/images/file_extension_icon/jpg.svg
   - assets/images/file_extension_icon/js.svg
   - assets/images/file_extension_icon/midi.svg
   - assets/images/file_extension_icon/mov.svg
   - assets/images/file_extension_icon/mp3.svg
   - assets/images/file_extension_icon/mpg.svg
   - assets/images/file_extension_icon/pdf.svg
   - assets/images/file_extension_icon/php.svg
   - assets/images/file_extension_icon/png.svg
   - assets/images/file_extension_icon/ppt.svg
   - assets/images/file_extension_icon/ps.svg
   - assets/images/file_extension_icon/psd.svg
   - assets/images/file_extension_icon/raw.svg
   - assets/images/file_extension_icon/sql.svg
   - assets/images/file_extension_icon/svg.svg
   - assets/images/file_extension_icon/tif.svg
   - assets/images/file_extension_icon/txt.svg
   - assets/images/file_extension_icon/wmv.svg
   - assets/images/file_extension_icon/xls.svg
   - assets/images/file_extension_icon/xml.svg
   - assets/images/file_extension_icon/zip.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
